---
- hosts: hifive
  become: yes
  become_user: root

  tasks:
    - name: Copy project/index.php
      copy:
        src: project/index.php
        dest: /var/www/html
        owner: apache
        group: apache
