image: dblaci/ubuntu-ssh-rsync

before_script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy_to_webserver:
 stage: deploy
 
 only:
   - master
   
 script:
   - rsync -av --exclude='project/.htaccess' project/* gitlab@35.180.10.123:/var/www/html


 when: manual

