---
- hosts: hifive
  become: yes
  become_user: root

  tasks:
    - name: Install amazon epel
      command: amazon-linux-extras install epel -y

    - name: Install phpMyAdmin
      yum:
        name: phpmyadmin
        state: latest

    - name: Create phpMyAdmin.conf
      template:
        src: phpMyAdmin.j2
        dest: /etc/httpd/conf.d/phpMyAdmin.conf
        force: yes
